[versions]
activityCompose = "1.9.0"
billingKtx = "6.2.1"
coilCompose = "2.6.0"
composeBomVersion = "2024.05.00"
constraintlayoutCompose = "1.0.1"
coreKtx = "1.13.1"
espressoCore = "3.5.1"
foundation = "1.6.7"
hiltNavigationCompose = "1.2.0"
junit = "4.13.2"
junitVersion = "1.1.5"
kotlinxCollectionsImmutable = "0.3.7"
lifecycleRuntimeCompose = "2.7.0"
lifecycleRuntimeKtx = "2.7.0"
material3 = "1.2.1"
materialIconsExtended = "1.6.7"
navigationCompose = "2.7.7"
orbitViewmodel = "6.1.0"
orbitCore = "6.1.0"
playServicesAuth = "21.1.1"
retrofit = "2.11.0"
okhttp = "4.12.0"
room = "2.6.1"
hilt = "2.51.1"
dataStore = "1.1.1"
security-crypto = "1.0.0"
streamLog = "1.1.4"
kakao-login = "2.19.0"
webRtc = "1.1.2"
android-library = "8.0.2"
jetbrains-plugin = "1.9.23"
android-application = "8.4.0"
appcompat = "1.6.1"
material = "1.12.0"
annotationJvm = "1.7.1"

[libraries]
# android
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-annotation-jvm = { group = "androidx.annotation", name = "annotation-jvm", version.ref = "annotationJvm" }

# test
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
junit = { module = "junit:junit", version.ref = "junit" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }

# lifecycle
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleRuntimeCompose" }

# compose libs
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
compose-coil = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
compose-constraintlayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayoutCompose" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBomVersion" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "foundation" }
compose-icons = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
compose-hilt-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

#Compose UI
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }

# play services
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
billing-ktx = { module = "com.android.billingclient:billing-ktx", version.ref = "billingKtx" }

# retrofit
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }

# okhttp
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }

# room
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

# hilt
hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }

# data store
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "dataStore" }
datastore-preferences-core = { group = "androidx.datastore", name = "datastore-preferences-core", version.ref = "dataStore" }

# crypto
security-crypto = { group = "androidx.security", name = "security-crypto", version.ref = "security-crypto" }

# webrtc
stream-log = { module = "io.getstream:stream-log", version.ref = "streamLog" }
stream-webrtc-android-compose = { module = "io.getstream:stream-webrtc-android-compose", version.ref = "webRtc" }
stream-webrtc-android-ui = { module = "io.getstream:stream-webrtc-android-ui", version.ref = "webRtc" }
webttc = { group = "io.getstream", name = "stream-webrtc-android", version.ref = "webRtc" }

#kakao
kakao-login = { module = "com.kakao.sdk:v2-user", version.ref = "kakao-login" }

# orbit
orbit-compose = { module = "org.orbit-mvi:orbit-compose", version.ref = "orbitCore" }
orbit-test = { module = "org.orbit-mvi:orbit-test", version.ref = "orbitViewmodel" }
orbit-viewmodel = { module = "org.orbit-mvi:orbit-viewmodel", version.ref = "orbitViewmodel" }
orbit-core = { module = "org.orbit-mvi:orbit-core", version.ref = "orbitCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-application" }
android-library = { id = "com.android.library", version.ref = "android-library" }
jetbrains-android = { id = "org.jetbrains.kotlin.android", version.ref = "jetbrains-plugin" }
jetbrains-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrains-plugin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

[bundles]
webrtc = ["webttc", "stream-webrtc-android-compose", "stream-webrtc-android-ui"]
orbit = ["orbit-compose", "orbit-viewmodel", "orbit-core"]
lifecycle = ["lifecycle-runtime-ktx", "androidx-lifecycle-runtime-compose"]
compose-ui = ["androidx-compose-ui", "androidx-compose-ui-graphics", "androidx-compose-ui-tooling-preview"]
compose-libs = ["compose-coil", "compose-navigation", "compose-constraintlayout", "compose-activity", "compose-foundation", "compose-icons", "compose-material3", "compose-hilt-navigation"]
room = ["room-ktx", "room-runtime"]
datastore = ["datastore-preferences", "datastore-preferences-core"]
network = ["retrofit", "retrofit-gson", "okhttp", "okhttp-logging"]
android-test = ["ext-junit", "espresso-core", "androidx-compose-ui-test"]
test = ["junit", "orbit-test"]
debug = ["androidx-compose-ui-tooling", "androidx-compose-ui-test-manifest"]